version: '3'
services:
  view:
    build:
      context: ./view
      dockerfile: Dockerfile
    container_name: 'view'
    ports:
      - 80:80
    depends_on:
      - server
    restart: always
  server:
    # 构建目录
    build:
      context: ./server
      dockerfile: Dockerfile
    # 容器名
    container_name: 'server'
    # 暴露端口
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: always